#!/usr/bin/php
<?php

// check permissions / rm old download files / ...


// download zip files
echo 'starting the download now ... '."\n";
$data = file_get_contents('https://github.com/evo42/runty/archive/installer.zip');
file_put_contents('runty-installer.zip', $data);
echo 'done. '."\n";

// unzip
echo 'unzip download'."\n";
$zip = new ZipArchive;
     $res = $zip->open('runty-installer.zip');
     if ($res === TRUE) {
         $zip->extractTo('runty-git/');
         $zip->close();
         echo 'unzip ok.'."\n";
         
         // mv directories
         echo 'delete old runty directory. ok'."\n";
         if (is_dir('./runty')) {
             // create zip backup
             deleteDirectory('./runty');
         }
         
         if (!is_dir('./uploads')) {
         mkdir('./uploads');
         echo 'created /uploads/ upload data directory.'."\n";
         
            }
            
         echo 'done. copy /runty/ now'."\n";
         rename('./runty-git/runty-installer/runty', './runty');
         echo 'updated /runty/'."\n";
         if (!is_dir('./.runty')) {
             rename('./runty-git/runty-installer/.runty', './.runty');
             echo 'added new /.runty/ user data directory.'."\n";
         }
         echo ' -- OK. open http://<your.domain.com>/runty/ in your browser to sign in and start editing your page.'."\n";
         deleteDirectory('./runty-git');
         deleteDirectory('./runty-installer.zip');
         
         
         echo 'start downloading minimal demo now. '."\n";
         $data = file_get_contents('https://raw.github.com/evo42/runty/master/Minimal.html');
         file_put_contents('./Minimal.html', $data);
         echo 'done ... '."\n";
         
         deleteDirectory('./runty-installer');
     } else {
         echo 'unzip failed!'."\n";
         echo ' -- ERROR. application not installed.'."\n";
     }
     
     

function deleteDirectory($dir) { 
    if (!file_exists($dir)) return true; 
    if (!is_dir($dir) || is_link($dir)) return unlink($dir); 
        foreach (scandir($dir) as $item) { 
            if ($item == '.' || $item == '..') continue; 
            if (!deleteDirectory($dir . "/" . $item)) { 
                chmod($dir . "/" . $item, 0777); 
                if (!deleteDirectory($dir . "/" . $item)) return false; 
            }; 
        } 
        return rmdir($dir); 
    }
?>